### ISSUE TITLE
Published package missing dist files

### ISSUE THREAD

**Issue by esatterwhite** [philsturgeon/spectral-documentation#11]
The 1.0.0 version of this package on npm defines exports that point to files in a `dist` directory, which do not exist in the published package.

Unless I'm missing something, the published package is unusable

## Current Behavior

Trying to require or import the module results in a `MODULE_NOT_FOUND` error being thrown because `dist/ruleset.{js,mjs,ts}` do not exists

## Expected Behavior

The package should be published with all necessary files

## Steps to Reproduce

1. Install package from npm
2. try to load it in a repl

**Comment by mnaumanali94** [comment]
Fixed with the latest release.
